FROM ubuntu:latest

# set environment vars
ENV HADOOP_HOME /opt/hadoop
ENV JARs opt/hadoop/share/hadoop/tools/lib/hadoop-streaming-3.3.6.jar
ENV HDFS_NAMENODE_USER="root"
ENV HDFS_DATANODE_USER="root"
ENV HDFS_SECONDARYNAMENODE_USER="root"
ENV YARN_RESOURCEMANAGER_USER="root"
ENV YARN_NODEMANAGER_USER="root"

# install packages
RUN \
  apt-get update && apt-get install -y \
  ssh \
  rsync \
  vim \
  openjdk-8-jdk


# download and extract hadoop, set JAVA_HOME in hadoop-env.sh, update path
# Ref: https://downloads.apache.org/hadoop/common/
# RUN \
#   wget https://downloads.apache.org/hadoop/common/hadoop-3.3.6/hadoop-3.3.6.tar.gz && \
#   tar -xzvf hadoop-3.3.6.tar.gz

# COPY file hadoop có sẵn ở local
COPY hadoop-3.3.6.tar.gz ..
RUN  tar -xzvf hadoop-3.3.6.tar.gz

# Move dir hadoop to /opt/hadoop
RUN  mv hadoop-3.3.6 /opt/hadoop

# set env for hadoop
RUN  echo "export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64" >> /opt/hadoop/etc/hadoop/hadoop-env.sh
RUN  echo "PATH=$PATH:/opt/hadoop/bin" >> ~/.bashrc

# create ssh keys
RUN \
  ssh-keygen -t rsa -P '' -f ~/.ssh/id_rsa && \
  cat ~/.ssh/id_rsa.pub >> ~/.ssh/authorized_keys && \
  chmod 0600 ~/.ssh/authorized_keys

# copy hadoop configs
ADD config/*xml /opt/hadoop/etc/hadoop/

# copy ssh config
ADD config/ssh_config /root/.ssh/config

# copy script to start hadoop
ADD config/start-hadoop.sh start-hadoop.sh